apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-m8-web-deployment-frontendbackend
  labels:
    app: first-m8-web
spec:
  replicas: 3 # placeholder amount, can change if need be
  selector:
    matchLabels:
      app: first-m8-web
  template:
    metadata:
      name: first-m8-web-pod-frontendbackend
      labels:
        app: first-m8-web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: first-m8-web-container-frontend
        image: # waiting for Alex to send docker hub path
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: first-m8-web-container-backend
        image: # waiting for Alex to send docker hub path
        imagePullPolicy: Always
        ports:
        - containerPort: 3000