apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: web
spec:
  containers:
  - name: first-m8-web-container-backend
    image: alexlee27/fm8-server
    imagePullPolicy: Always
    ports:
    - containerPort: 3000