apiVersion: v1
kind: Service
metadata:
  name: first-m8-web-service
spec:
  type: NodePort # will most likely eventually change to LoadBalancer to make it available via the cloud
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31000
    protocol: TCP
  selector:
    app: first-m8-web