global:
  scrape_interval: 15s

scrap_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'grafana'

    static_configs:
    - targets: ['localhost:3000']