# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Build and push landing page server and client
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./landing-page
          file: ./landing-page/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/firstm8landingpage:latest

    
      - name: Build and push prometheus
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./prometheus
          file: ./prometheus/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-prometheus:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: first-m8-landingpage
          environment_name: firstm8landingpage-prod
          region: us-east-2